const demo = {
    current: {
        artistAppearances: {
            'Taylor Swift': 723,
            'Ed Sheeran': 589,
            'Ariana Grande': 542,
            'Post Malone': 481,
            'Beyoncé': 376,
            'The Weeknd': 345,
            'Billie Eilish': 322,
            'Bruno Mars': 309,
            'Cardi B': 285,
            'Shawn Mendes': 260
        },
        songAppearances: {
            'Shape of You': 145,
            'Blinding Lights': 130,
            'Thank U, Next': 122,
            'Circles': 118,
            'Bad Guy': 115,
            'Senorita': 110,
            'Drivers License': 105,
            'Old Town Road': 100,
            'Levitating': 98,
            'Havana': 95
        },
        songs: 9120,
        minutesPlayed: 18256,
        hoursPlayed: 304,
        daysPlayed: 13,
        uniqueArtists: [
            'Taylor Swift',
            'Ed Sheeran',
            'Ariana Grande',
            'Post Malone',
            'Beyoncé',
            'The Weeknd',
            'Billie Eilish',
            'Bruno Mars',
            'Cardi B',
            'Shawn Mendes',
            'Lady Gaga',
            'Justin Bieber',
            'Dua Lipa',
            'Rihanna',
            'Harry Styles',
            'Maroon 5',
            'Doja Cat',
            'Katy Perry',
            'Sam Smith',
            'Halsey',
            'Coldplay',
            'Imagine Dragons',
            'Selena Gomez',
            'Adele',
            'Lizzo',
            'Drake',
            'Miley Cyrus',
            'SZA',
            'Olivia Rodrigo',
            'Lana Del Rey',
            'Camila Cabello',
            'Charlie Puth',
            'Nicki Minaj',
            'Jonas Brothers',
            'Zayn',
            'BTS',
            'BLACKPINK',
            'EXO',
            'TWICE',
            'NCT',
            'Monsta X',
            'Red Velvet',
            'Stray Kids',
            'TXT',
            'ITZY',
            'ATEEZ',
            'ENHYPEN',
            'SEVENTEEN',
            'SHINee',
            'SuperM',
            'BigBang',
            '2NE1',
            'G-Dragon',
            'Taeyeon',
            'IU',
            'Lee Hi',
            'Sunmi',
            'Chungha',
            'Somi',
            'HyunA',
            'CL',
            'Jessie J',
            'Bebe Rexha',
            'Ava Max',
            'Tones and I',
            'Sia',
            'Ellie Goulding',
            'Zara Larsson',
            'Demi Lovato',
            'Kehlani',
            'Alessia Cara',
            'Tori Kelly',
            'Rita Ora',
            'Bebe Rexha',
            'Janelle Monáe',
            'H.E.R.',
            'Kehlani',
            'Normani',
            'Maggie Rogers',
            'FKA Twigs',
            'BANKS',
            'Troye Sivan',
            'Lauv',
            'Khalid',
            'James Arthur',
            'Lewis Capaldi',
            'Conan Gray',
            'Ruel',
            'Shawn Mendes',
            'Jacob Collier',
            'Rex Orange County',
            'Joji',
            'HONNE',
            'LANY',
            'The 1975',
            'Glass Animals',
            'Tame Impala',
            'Mac DeMarco',
            'Clairo',
            'Gorillaz',
            'Arctic Monkeys',
            'Cage The Elephant',
            'Florence + The Machine',
            'Hozier',
            'Lorde'
        ],
        minutesPerArtist: [
            { artist: 'Taylor Swift', minutes: 1760 },
            { artist: 'Ed Sheeran', minutes: 1485 },
            { artist: 'Ariana Grande', minutes: 1352 },
            { artist: 'Post Malone', minutes: 1275 },
            { artist: 'Beyoncé', minutes: 1040 },
            { artist: 'The Weeknd', minutes: 965 },
            { artist: 'Billie Eilish', minutes: 892 },
            { artist: 'Bruno Mars', minutes: 857 },
            { artist: 'Cardi B', minutes: 812 },
            { artist: 'Shawn Mendes', minutes: 768 }
        ],
        user: {
            displayName: 'musicLover123',
            imageUrl: 'https://example.com/image/musiclover123.jpg'
        }
    },
    allTime: {
        artistAppearances: {
            'Taylor Swift': 723,
            'Ed Sheeran': 589,
            'Ariana Grande': 542,
            'Post Malone': 481,
            'Beyoncé': 376,
            'The Weeknd': 345,
            'Billie Eilish': 322,
            'Bruno Mars': 309,
            'Cardi B': 285,
            'Shawn Mendes': 260
        },
        songAppearances: {
            'Shape of You': 145,
            'Blinding Lights': 130,
            'Thank U, Next': 122,
            'Circles': 118,
            'Bad Guy': 115,
            'Senorita': 110,
            'Drivers License': 105,
            'Old Town Road': 100,
            'Levitating': 98,
            'Havana': 95
        },
        songs: 9120,
        minutesPlayed: 18256,
        hoursPlayed: 304,
        daysPlayed: 13,
        uniqueArtists: [
            'Taylor Swift',
            'Ed Sheeran',
            'Ariana Grande',
            'Post Malone',
            'Beyoncé',
            'The Weeknd',
            'Billie Eilish',
            'Bruno Mars',
            'Cardi B',
            'Shawn Mendes',
            'Lady Gaga',
            'Justin Bieber',
            'Dua Lipa',
            'Rihanna',
            'Harry Styles',
            'Maroon 5',
            'Doja Cat',
            'Katy Perry',
            'Sam Smith',
            'Halsey',
            'Coldplay',
            'Imagine Dragons',
            'Selena Gomez',
            'Adele',
            'Lizzo',
            'Drake',
            'Miley Cyrus',
            'SZA',
            'Olivia Rodrigo',
            'Lana Del Rey',
            'Camila Cabello',
            'Charlie Puth',
            'Nicki Minaj',
            'Jonas Brothers',
            'Zayn',
            'BTS',
            'BLACKPINK',
            'EXO',
            'TWICE',
            'NCT',
            'Monsta X',
            'Red Velvet',
            'Stray Kids',
            'TXT',
            'ITZY',
            'ATEEZ',
            'ENHYPEN',
            'SEVENTEEN',
            'SHINee',
            'SuperM',
            'BigBang',
            '2NE1',
            'G-Dragon',
            'Taeyeon',
            'IU',
            'Lee Hi',
            'Sunmi',
            'Chungha',
            'Somi',
            'HyunA',
            'CL',
            'Jessie J',
            'Bebe Rexha',
            'Ava Max',
            'Tones and I',
            'Sia',
            'Ellie Goulding',
            'Zara Larsson',
            'Demi Lovato',
            'Kehlani',
            'Alessia Cara',
            'Tori Kelly',
            'Rita Ora',
            'Bebe Rexha',
            'Janelle Monáe',
            'H.E.R.',
            'Kehlani',
            'Normani',
            'Maggie Rogers',
            'FKA Twigs',
            'BANKS',
            'Troye Sivan',
            'Lauv',
            'Khalid',
            'James Arthur',
            'Lewis Capaldi',
            'Conan Gray',
            'Ruel',
            'Shawn Mendes',
            'Jacob Collier',
            'Rex Orange County',
            'Joji',
            'HONNE',
            'LANY',
            'The 1975',
            'Glass Animals',
            'Tame Impala',
            'Mac DeMarco',
            'Clairo',
            'Gorillaz',
            'Arctic Monkeys',
            'Cage The Elephant',
            'Florence + The Machine',
            'Hozier',
            'Lorde'
        ],
        minutesPerArtist: [
            { artist: 'Taylor Swift', minutes: 1760 },
            { artist: 'Ed Sheeran', minutes: 1485 },
            { artist: 'Ariana Grande', minutes: 1352 },
            { artist: 'Post Malone', minutes: 1275 },
            { artist: 'Beyoncé', minutes: 1040 },
            { artist: 'The Weeknd', minutes: 965 },
            { artist: 'Billie Eilish', minutes: 892 },
            { artist: 'Bruno Mars', minutes: 857 },
            { artist: 'Cardi B', minutes: 812 },
            { artist: 'Shawn Mendes', minutes: 768 }
        ]
    },
    user: {
        displayName: "demoUser",
        imageUrl: "https://example.com/image/demoUser.jpg"
    }
}

console.log(JSON.stringify(demo))